services:

  gingko-server:

    build:
      context: gingko
      dockerfile: server.Dockerfile

  gingko-worker:

    build: 
      context: gingko
      dockerfile: worker.Dockerfile 


  gingko-web:

    build:
      context: gingko-web
      dockerfile: web.Dockerfile

  caddy:
    image: caddy:latest
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro  

  redis:
    image: redis:latest
    volumes:
      - redis:/data
  
volumes:
  redis: